export const UserDataConstants = {
    IMPORT_CUSTOMER_MAPPING: `IMPORT_CUSTOMER_MAPPING`,
    IMPORT_USER_MAPPING: `IMPORT_USER_MAPPING`,

    IMPORT_INVENTORY_MAPPING: `IMPORT_INVENTORY_MAPPING`,

    IMPORT_CATEGORY_MAPPING: `IMPORT_CATEGORY_MAPPING_`,
    IMPORT_BILL_MAPPING: `IMPORT_BILL_MAPPING`,
    IMPORT_PURCHASE_REQUEST_MAPPING: `IMPORT_PURCHASE_REQUEST_MAPPING`,
    IMPORT_PURCHASE_ORDER_MAPPING: `IMPORT_PURCHASE_ORDER_MAPPING`,
    IMPORT_BILL_DETAIL_MAPPING: `IMPORT_BILL_DETAIL_MAPPING`,
    IMPORT_PRODUCT_MAPPING: `IMPORT_PRODUCT_MAPPING`,
}
